In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#Select a number from array
arr[8]

8

In [6]:
#Select numbers from array :Slice operation
arr [1:5]

array([1, 2, 3, 4])

In [7]:
#This will update the value of elemets from index 0 to 4 to 100
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#Create a copy of the array

arr_copy = arr.copy()
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])