In [11]:
import numpy as np

In [15]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#Select a number from array
arr[8]

8

In [6]:
#Select numbers from array :Slice operation
arr [1:5]

array([1, 2, 3, 4])

In [5]:
#This will update the value of elemets from index 0 to 4 to 100
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [6]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#Create a copy of the array

arr_copy = arr.copy()
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#2 D Array

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#This selects the first element of the array

arr_2d[0][0]

1

In [9]:
#This selects the entire first row

arr_2d[0]

array([1, 2, 3])

In [13]:
#Slice operation in 2 D Array

arr_2d[:2,1:]   #Slice upto 2nd row and from 1st column

array([[2, 3],
       [5, 6]])

In [16]:
bool_arr = arr>5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [17]:
arr[bool_arr] 
#This returns the values only greater than 5 in the array    or  (In short ) arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [19]:
 arr + arr  #Adds array digit by digit according to index

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
arr *arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [24]:
arr * 100 #Multiplies individual elements in array with a scalar

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [31]:
arr ** 2  #Array to power of two

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

# Universal Array Functions

In [30]:
np.sqrt(arr)  #Square Root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [28]:
np.exp(arr) #Exponential Function

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [29]:
np.sin(arr)   #Similarly cosine , log etc.

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])