In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#Select a number from array
arr[8]

8

In [6]:
#Select numbers from array :Slice operation
arr [1:5]

array([1, 2, 3, 4])

In [5]:
#This will update the value of elemets from index 0 to 4 to 100
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [6]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#Create a copy of the array

arr_copy = arr.copy()
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#2 D Array

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#This selects the first element of the array

arr_2d[0][0]

1

In [9]:
#This selects the entire first row

arr_2d[0]

array([1, 2, 3])

In [13]:
#Slice operation in 2 D Array

arr_2d[:2,1:]   #Slice upto 2nd row and from 1st column

array([[2, 3],
       [5, 6]])