# NumPy Array

We can cast a python list into an array using numpy.

In [4]:
#1-D  ARRAY

import numpy as np
my_list = [1,2,3,4,5]
arr = np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [5]:
#2-D ARRAY

import numpy as np
arr = [[1,2,3],[3,4,5]]
twod = np.array(arr)
twod

array([[1, 2, 3],
       [3, 4, 5]])

In [6]:
np.arange(0,11,2)   #(start@0 , stop@11 , steps@2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(5)   # One dimentional array of 0's

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,3)) #Two dimentional array of 0's

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(2)

array([1., 1.])

In [14]:
np.linspace(0,5,10)  #This gives 10 evenly space points between 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
#Identity Matrix 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
#Random matrix 

np.random.rand(5,5)

array([[0.8720368 , 0.46947143, 0.72177695, 0.7272314 , 0.68535591],
       [0.49447885, 0.42725888, 0.17608934, 0.20241724, 0.19012698],
       [0.78461755, 0.72977959, 0.44942105, 0.62917781, 0.15330837],
       [0.46743475, 0.63775751, 0.61515016, 0.78083267, 0.25744458],
       [0.07230131, 0.94669053, 0.52353079, 0.72267599, 0.11074964]])

In [26]:
np.random.randint(1,100,10)  #Gives 10 random number between 1 to 99  (Since 100 is not included)

array([96,  5, 20, 67, 83,  6, 50, 51,  4, 33])

In [27]:
arr = np.arange(0,50)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [29]:
arr.reshape(5,10)  #An error occurs if the values required to fill the matrix is less than the total number of elements in the array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [31]:
arr.max()  #Maximum random value in the array  (Similarly arr.min() gives minimum value)

49

In [34]:
arr.argmax()  #Returns the index of maximum element in the array  (Similarly arr.argmin())

49